bits: 5, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
bits: 5, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
bits: 7, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
bits: 7, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
bits: mixed, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
bits: mixed, num_examples_mode: 1, dataset_size: 200000, error_prob: 0 
Traceback (most recent call last):
  File "/home/riadas/in-context-learning/src/rational_rules/generative_model/bulk_data_generation.py", line 32, in <module>
    gen_train_and_test_data(0.8, num_formulas=num_prompts, num_vectors_per_formula=num_examples, feature_dim=num_bits, min_clauses=1, mixed_pos_and_neg=mixed_pos_and_neg, format_labels=True, error_prob=error_prob)
  File "/home/riadas/in-context-learning/src/rational_rules/generative_model/generate_train_test_data.py", line 120, in gen_train_and_test_data
    formulas, prompts = gen_feature_vectors_and_labels(num_formulas, num_vectors_per_formula, feature_dim, min_clauses, mixed_pos_and_neg, format_labels, error_prob)
  File "/home/riadas/in-context-learning/src/rational_rules/generative_model/generate_train_test_data.py", line 80, in gen_feature_vectors_and_labels
    query = int_to_bit_vector(random.sample(unseen_ints, 1)[0], feature_dim)
  File "/data/riadas/miniconda3/envs/rule-induction/lib/python3.9/random.py", line 449, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
